# Generated by Django 2.1.15 on 2022-10-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
